CREATE DATABASE MyAppDb
GO

USE MyAppDb
GO

CREATE SCHEMA MyAppSchema
GO

CREATE TABLE MyAppSchema.Users
(
    Id INT PRIMARY KEY IDENTITY(1,1),
    Email NVARCHAR(200) NOT NULL,
    FirstName NVARCHAR(50) NOT NULL,
    LastName NVARCHAR(50) NOT NULL,
    PasswordHash VARBINARY(MAX) NOT NULL,
    PasswordSalt VARBINARY(MAX) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT UQ_Users_Email UNIQUE (Email)
);

SELECT * FROM MyAppSchema.Users